### ISSUE TITLE
Corrupted Images

### ISSUE THREAD

**Issue by EricZimmermann** [cropandweed/cropandweed-dataset#1] opened 2023-03-23 20:12 UTC
Hello, 

It seems as though some images are corrupted and have annotations in these problematic regions.
ex: ave-0357-0008.jpg (gray band bottom of image which is displayed below)

Here are some other images which experience similar problems:
- ave-0506-0007.jpg
- ave-0527-0009.jpg

It seems like there are quite a few images that have these problems. Is there an updated version or is this to be expected?

![ave-0357-0008](https://user-images.githubusercontent.com/23340179/227340487-af9ae41b-2590-4d82-b438-12babf79a7c1.jpg)

**Comment by EricZimmermann** [comment] 2023-03-23 20:20
As a follow up, here is a corrupted sample (ave-0506-0007.jpg) with the annotations tacked on for visualization purposes. It was the only image within the recording session that had an issue.

![image](https://user-images.githubusercontent.com/23340179/227343045-cb1fe5e6-1626-4b10-9bf4-f3482f04de66.png)

**Comment by steiningerd** [comment] 2023-04-24 00:56
Hi,
thank you for identifying the corrupted images. The issue is fixed in the latest update. Additionally, we validated all the other images in the dataset.

**Closed as completed by steiningerd** 2023-04-24 00:56 UTC
